version: '3'

services:

  songs_app:
    build: .
    environment:
      - PYTHONPATH=/app
      - ROOT_PATH=/app
      - SONGS_APP_CONFIG=docker_debug
      - SONGS_APP_DB=mongodb://songs_user:songs_pass@mongo:27017/songs_db?authSource=admin
    depends_on:
      - mongo
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: app

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: songs_user
      MONGO_INITDB_ROOT_PASSWORD: songs_pass

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: songs_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: songs_pass

  functests:
    build:
      context: .
      dockerfile: ./functests/Dockerfile
    command: sleep
