version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: songs_user
      MONGO_INITDB_ROOT_PASSWORD: songs_pass

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: songs_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: songs_pass

